### ISSUE TITLE
Bundle the JAR with the extension

### ISSUE THREAD

**Issue by felipecrs** [DontShaveTheYak/groovy-guru#13]
Just a suggestion. I do this with the ShellCheck extension, and by doing so you would be able to remove the dependency on the file downloader and further interactions with the user about downloading the language server.

Awesome initiative btw!

**Comment by shadycuz** [comment]
Yeah it makes sense. When I first set it up I had no idea that the the `vsce` command was bundling all files into the final extension. I was also kinda concerned about extension size but not sure it even matters. 

I was kicking around the idea of being able to specify the path to an external LS binary, mainly for development stuff. I think when I implement that I will bundle the LS into the extension file.

**Comment by shadycuz** [comment]
@felipecrs I have rebased the plugin onto `yo code`. That should make it easier for people to use and contribute. Basically just switching to yarn from gradle and using more standardized tooling. This allowed me to finally be able to hit `f5` and run/debug the extension properly.

I also took the time to bundle the language server in the extension like you asked. This has already been shipped and you should be seeing the update soon. Though I'm not sure if it will auto update or what? 

In the next feature release (next week or so), we will be adding docStrings on [hover](https://github.com/GroovyLanguageServer/groovy-language-server/pull/51). 🚀 🚀 🚀 🌔

**Comment by felipecrs** [comment]
This is amazing!

> Though I'm not sure if it will auto update or what?

Yes, VS Code extensions always auto-update. I just tested here, it's very nice, the installation is now flawless.

> In the next feature release (next week or so), we will be adding docStrings on hover. 🚀 🚀 🚀 🌔

Can't wait! :-D

**Comment by shadycuz** [comment]
@felipecrs v0.3.0 is out and has docstring support. 🚀

**Comment by felipecrs** [comment]
Wow, just tested it out here. Awesome!

![image](https://user-images.githubusercontent.com/29582865/129488539-0788fec0-1bd0-4bdb-8396-088b830f7aff.png)
