### ISSUE TITLE
extension activates but auto-completeion isn't working

### ISSUE THREAD

**Issue by dudukk1312** [DontShaveTheYak/groovy-guru#20]
Hi,

I tried many times but the code suggestion didn't appear when I type.
I tried exactly the same as your demo on the main page, but it doesn't work.
The language server run and took over 800MB of RAM.
![image](https://user-images.githubusercontent.com/33556384/130592934-931d1815-52d3-4aaa-9b0c-edd243357854.png)
I download and set the lib path to groovy SDK lib, but it still doesn't work.
Did I miss something?

**Comment by dudukk1312** [comment]
@shadycuz 
there is it, please take it F.Y.I
Version: 1.59.1 (user setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by shadycuz** [comment]
@dudukk1312 Can you do `ctrl + shift + p` and search for "Open Settings (JSON)". 

In that JSON file can you set the following value `"groovy.trace.server": "verbose"`

Then reload your window and you should see lots of information in the `Groovy Language Server` log tab. 

I cleared mine and then hovered over `users` and got this: 

```
[Trace - 11:05:15 AM] Sending request 'textDocument/hover - (33)'.
Params: {
    "textDocument": {
        "uri": "file:///home/shadycuz/repos/dsty/testGroovy/test.groovy"
    },
    "position": {
        "line": 0,
        "character": 8
    }
}


[Trace - 11:05:15 AM] Received response 'textDocument/hover - (33)' in 1ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```groovy\nList users\n```\n"
    }
}
```

**Comment by shadycuz** [comment]
If you are still having issues then feel free to reply.
