### ISSUE TITLE
Does not work on latest vscode (1.65 windows)

### ISSUE THREAD

**Issue by joelBrun** [DontShaveTheYak/groovy-guru#27]
At startup, the server does not move from the message "Groovy-guru is starting".

No intellisense works on the groovy code source.

**Comment by shadycuz** [comment]
Thanks for reporting, testing this now.

**Comment by shadycuz** [comment]
@joelBrun I just tried it on `1.64.1` and it worked. Did this work before for you? In your terminal, if you go to `output` tab and then find the logs for `Groovy Language Server` is there any errors?

**Comment by shadycuz** [comment]
@joelBrun Can you try one of the examples from the README.md? Make sure you save the file with a `.groovy` extension. The saving part is really important. It wont work with a file that has not been saved yet.
