### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by noraj** [DontShaveTheYak/groovy-guru#28]
Hi can you push your extension to https://open-vsx.org/ in addition to VSCode Market Place so people using the FLOSS version could install it too?

I wrote [an article](https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/) on the subject.

Example of Github Action: https://github.com/HaaLeo/publish-vscode-extension

**Comment by shadycuz** [comment]
I have manually published the extension https://open-vsx.org/extension/DontShaveTheYak/groovy-guru

I have made sure that future releases will publish along side the vscode marketplace in this PR #30 

I have requested namespace ownership https://github.com/EclipseFdn/open-vsx.org/issues/960

Thanks for the reminder about the open source version of vscode and its marketplace <3

**Comment by noraj** [comment]
Awesome! Thanks for the work.
