### ISSUE TITLE
Language Server won't start

### ISSUE THREAD

**Issue by mphelps1978** [DontShaveTheYak/groovy-guru#29]
I cannot get the language server to start. The message I get is simply "Internal Error" The Output from Language Server is empty, the thumb is down, and I cannot get any other information.

I'm in a bit of a different scenario with my environment - I run VSCode on a windows-based desktop, but I use remoteSSH to an Ubuntu 20.08 Server host that is on my network, which is where I do all of my work. 

Java is installed on both host and guest, and I've tried the path for both Windows and Ubuntu installs, and I get the same result. 

What really gets me is that, despite adding the logging: verbose option that I saw in another issue thread, the output is still completely blank. 

Anything else I could be missing?

**Comment by mphelps1978** [comment]
Can close this. I just realized this is in regards to the code-groovy extension.. Sorry

**Comment by mphelps1978** [comment]
OK So Apparently it is groovy-guru causing it.. I can't get the language server to start. I keep getting an error:

_The groovy.java.home setting does not point to a valid JDK_

My settings.json:

`"[groovy]": {
        
        "editor.defaultFormatter": "NicolasVuillamy.vscode-groovy-lint",
        "groovy.trace.server": "verbose",
        "groovy.java.configuration.runtimes": [
            {
                "name":"Java 1.8",
                "path": "C:\\Program Files\\Java\\jdk1.8.0_311"
            }
        ],
        // "groovy.java.home": "C:\\Program Files\\Java\\jdk1.8.0_311"
    },
    
    "update.mode": "manual",
    "update.enableWindowsBackgroundUpdates": false,
    
    
    "workbench.activityBar.visible": false,
    "groovy.java.home": "C:\\Program Files\\Java\\jdk1.8.0_311\\"`

I'm wondering if I need to point to my Ubuntu Java install?

**Comment by shadycuz** [comment]
So usually I recommend people dont feel out the path variables unless they want to point to a certain version of java. Because the plugin will auto detect the location of the java binary on the machine. I haven't actually used the plugin in the context of a remote SSH machine and I wonder if that environment requires something different. 

If I give you a public key, can you create a user on your ubuntu machine and add that key to it? That way I can setup the remoteSSH plugin and connect to the same machine as you and try and figure out what is going on.

If you cant then that is okay, I can probably try it on a machine at work. I'm just not sure if it will the exact version of ubuntu.

**Comment by mphelps1978** [comment]
Unfortunately I can't do that.. my ISP has strict rules for incoming connections, and they give me 0 control over the firewall on their router without paying an additional arm and a leg for an already overpriced service 😐

**Comment by shadycuz** [comment]
Ill try and set up a test environment this weekend.

**Comment by mphelps1978** [comment]
Thank you so much. This has been driving me insane lol -  I'll keep an eye on the thread.

**Comment by shadycuz** [comment]
@mphelps1978 

Here is what I learned. 

* Everything happens in the remote SSH server. So it doesn't matter if you have `java` and the `groovy-guru` extension installed in your local workspace. Once you connect to the remote ssh server, you will need to install the extension again and the java. 

* The confusing thing, is that if you set `groovy.java.home` in your user preferences, it will try to use that in your remote ssh. So dont set `groovy.java.home` at all. 

* The other confusing this is `groovy.java.home` is not asking for the path to the java binary 👎, it actually adds `/bin/java` to what ever `groovy.java.home` is pointing to. So if my java is `/usr/bin/java` and it was after installing with `apt install default-jre`. Then I need to set `groovy.java.home: "/usr"` to get it to work right 🙄 .

* Even after I installed java, it didn't seem to work until I disconnected and re-connected to the SSH machine. You could probably just get away with `ctrl+shift+p` and "Reload window". 


My recommendation is to let it auto discover java by not specifying the `groovy.java.home` setting, if that fails then run `which java` and set it but keep in mind that the extension appends `/bin/java` to `groovy.java.home`. 

Let me know if this fixes it, if not we can have a screen share session. I used `apt install default-jre` which gave me:

```
root@ubuntu-s-1vcpu-1gb-nyc2-01:~# java -version
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

and the extension appears to be working correctly with java 11 in my tiny tests I have tried.
