### ISSUE TITLE
Unable to access jarfile on Windows

### ISSUE THREAD

**Issue by fdaguin** [DontShaveTheYak/groovy-guru#9]
### Expected Behavior

Groovy LSP starts correctly on Windows.

### Actual Behavior

The extension successfully downloads `groovy-language-server-X.X.X-all.jar` (in my case at `C:\Users\Admin\AppData\Roaming\Code\User\globalStorage\dontshavetheyak.groovy-guru\file-downloader-downloads\groovy-language-server-0.1.1-all.jar`). However, it does not find it:

![image](https://user-images.githubusercontent.com/72013963/125351110-f793f800-e35f-11eb-8dc1-0161c391c357.png)

Groovy Language Server output:

```text
Error: Unable to access jarfile /c:/Users/Admin/AppData/Roaming/Code/User/globalStorage/dontshavetheyak.groovy-guru/file-downloader-downloads/groovy-language-server-0.1.1-all.jar
[Info  - 22:20:45] Connection to server got closed. Server will restart.
[Error - 22:20:45] Connection to server is erroring. Shutting down server.
Error: Unable to access jarfile /c:/Users/Admin/AppData/Roaming/Code/User/globalStorage/dontshavetheyak.groovy-guru/file-downloader-downloads/groovy-language-server-0.1.1-all.jar
```` 

### Steps to Reproduce the Problem

1. Open a workspace with a `.groovy` file on Windows

### Possible solutions

There is an extra `/` at the begining of the path being resolved: `/c:/Users/Admin/AppData/Roaming/Code/User/globalStorage/dontshavetheyak.groovy-guru/file-downloader-downloads/groovy-language-server-0.1.1-all.jar`.

### Environment

- OS: Windows 10
- Extension version: 0.1.1
- Installation method: VSCode Marketplace

**Comment by shadycuz** [comment]
@fdaguin Thanks for reporting this. I will have to set up an environment to replicate but it looks like maybe it's an issue with the library I used to handle the download, as it returns the file path.

**Comment by shadycuz** [comment]
@fdaguin Did it automatically find your java installation? I tried SE but it was not able to find it. I tried manually configuring it but it doesn't seem to like the spaces `"groovy.java.home": "C:\Program Files (x86)\Java\jre1.8.0_291\bin\java.exe"`

**Comment by fdaguin** [comment]
@shadycuz The extension did not complain about Java. I both tested:

- using the extension setting `groovy.java.home` (in my case: `"groovy.java.home": "D:\\IDE\\jdk\\java-1.8.0-openjdk-1.8.0.111-3"`)
- relying on the `JAVA_HOME` environment variable

**Comment by fdaguin** [comment]
Thanks a lot for your investigation @shadycuz !

**Comment by shadycuz** [comment]
@fdaguin It was a rookie mistake, the new extension should be out in the next 20 mins, or you can manually install the vsix file from the [releases page](https://github.com/DontShaveTheYak/groovy-guru/releases/tag/0.1.2-SNAPSHOT).

**Comment by shadycuz** [comment]
@fdaguin New version is [live](https://marketplace.visualstudio.com/items?itemName=DontShaveTheYak.groovy-guru). Re-open if this doesn't resolve the error. Thanks for opening this issue. I will need to test on both machines going forward. 

Features are basic right now, but we have some cool stuff coming up like groovydoc support.

**Comment by fdaguin** [comment]
@shadycuz The bug is indeed fixed. Thanks a lot for your reactivity!
